name: CI and CD to Itch 
 
on: 
  push: 
    branches: 
      - main 
 
jobs: 
  buildAndTestForLinuxBasedPlatforms: 
    name: Build for ${{ matrix.targetPlatform }} 
    runs-on: ubuntu-latest 
    strategy: 
      fail-fast: false 
      matrix: 
        projectPath: [game] 
        targetPlatform: [WebGL, StandaloneWindows] 
        include:  
          - targetPlatform: StandaloneWindows 
            buildPath: '/'
            buildChannel: windows
          - targetPlatform: WebGL 
            buildPath: /ourhillofstars/
            buildChannel: webgl
 
    steps: 
      - name: Checkout repository 
        uses: actions/checkout@v2 
      - name: Cache Library 
        uses: actions/cache@v2 
        with: 
          path: ${{ matrix.projectPath }}/Library 
          key: Library-${{ matrix.targetPlatform }} 
          restore-keys: Library- 
      - name: Build project 
        uses: game-ci/unity-builder@v2 
        env: 
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }} 
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }} 
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }} 
        with: 
          buildName: ourhillofstars 
          projectPath: ${{ matrix.projectPath }} 
          versioning: Semantic 
          unityVersion: 2021.3.16f1 
          targetPlatform: ${{ matrix.targetPlatform }} 
          buildsPath: build 
      # - name: Display structure of build files 
      #   run: ls -R 
      #   working-directory: /home/runner 
      # - uses: actions/upload-artifact@v2 
      #   with: 
      #     name: Build-${{ matrix.targetPlatform }} 
      #     path: build/${{ matrix.targetPlatform }} 
      - name: Upload to itch 
        uses: KikimoraGames/itch-publish@v0.0.3 
        with: 
          butlerApiKey: ${{secrets.BUTLER_API_KEY}} 
          gameData: ./build/${{ matrix.targetPlatform }}${{ matrix.buildPath }} 
          itchUsername: ${{secrets.ITCH_USERNAME}} 
          itchGameId: ${{secrets.ITCH_GAME_ID}} 
          buildChannel: ${{ matrix.buildChannel }} 